### ISSUE TITLE
Fix integration with annotations

### ISSUE THREAD

**Issue by sloria** [chrisseto/django-include#1]
`.include` breaks when used together with `.annotate` with the following error: 

```
ProgrammingError: could not identify an equality operator for type json
```

**Comment by aaxelb** [comment]
It breaks with the same error when used with `.distinct`:
```
ProgrammingError: could not identify an equality operator for type json
LINE 1: SELECT DISTINCT (SELECT JSON_BUILD_ARRAY(...
                        ^
```

**Comment by sloria** [comment]
Here's the JIRA ticket for this: https://openscience.atlassian.net/browse/OSF-7746

**Comment by chrisseto** [comment]
@sloria This should be fixed in most cases by [this](https://github.com/chrisseto/django-include/blob/master/include/expressions.py#L177). See [this test](https://github.com/chrisseto/django-include/blob/master/tests/test_include.py#L30)
@aaxelb `.distinct` won't work unless django adds (or already has) `.distinct_on` or something like that.

**Comment by sloria** [comment]
Thanks @chrisseto !
